/*
================================================================================
  ORACLE DATABASE SECURITY REMEDIATION MASTER SCRIPT
================================================================================
  Purpose:  Comprehensive security hardening for Oracle Autonomous Database
  Version:  1.0.0
  Author:   Generated by oracle-dba skill

  USAGE:
    1. Set DRY_RUN to TRUE for preview mode (no changes made)
    2. Review output carefully
    3. Set DRY_RUN to FALSE to apply changes
    4. Run during maintenance window

  PREREQUISITES:
    - ADMIN or DBA privileges
    - Unified Auditing enabled (default in ADB)

  WARNING: Test in non-production first!
================================================================================
*/

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET FEEDBACK OFF

-- ============================================================================
-- CONFIGURATION
-- ============================================================================
DEFINE DRY_RUN = TRUE          -- Set to FALSE to apply changes
DEFINE EXCLUDE_USERS = 'SYS,SYSTEM,ADMIN,PDBADMIN,AUDSYS,DBSFWUSER'
DEFINE INACTIVE_DAYS = 90       -- Lock users inactive for this many days
DEFINE AUDIT_RETENTION_DAYS = 180

-- ============================================================================
-- REMEDIATION LOG TABLE
-- ============================================================================
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'SECURITY_REMEDIATION_LOG';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE security_remediation_log (
        log_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        run_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
        run_mode      VARCHAR2(10),
        category      VARCHAR2(50),
        action_type   VARCHAR2(50),
        target_object VARCHAR2(200),
        details       VARCHAR2(4000),
        status        VARCHAR2(20),
        error_message VARCHAR2(4000)
      )';
    DBMS_OUTPUT.PUT_LINE('Created security_remediation_log table');
  END IF;
END;
/

-- ============================================================================
-- MASTER REMEDIATION PACKAGE
-- ============================================================================
CREATE OR REPLACE PACKAGE security_remediation AS

  -- Configuration
  g_dry_run       BOOLEAN := &DRY_RUN;
  g_run_id        VARCHAR2(20) := TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS');
  g_exclude_users VARCHAR2(500) := '&EXCLUDE_USERS';

  -- Counters
  g_issues_found    NUMBER := 0;
  g_issues_fixed    NUMBER := 0;
  g_issues_skipped  NUMBER := 0;

  -- Main procedures
  PROCEDURE run_full_remediation;
  PROCEDURE revoke_dangerous_privileges;
  PROCEDURE revoke_public_grants;
  PROCEDURE lock_inactive_accounts;
  PROCEDURE enforce_password_policy;
  PROCEDURE enable_audit_policies;
  PROCEDURE setup_data_redaction;
  PROCEDURE generate_report;

  -- Utilities
  PROCEDURE log_action(
    p_category    VARCHAR2,
    p_action_type VARCHAR2,
    p_target      VARCHAR2,
    p_details     VARCHAR2,
    p_status      VARCHAR2 DEFAULT 'SUCCESS',
    p_error       VARCHAR2 DEFAULT NULL
  );

  FUNCTION is_excluded_user(p_username VARCHAR2) RETURN BOOLEAN;

END security_remediation;
/

CREATE OR REPLACE PACKAGE BODY security_remediation AS

  -- ===========================================================================
  -- UTILITY: Log Action
  -- ===========================================================================
  PROCEDURE log_action(
    p_category    VARCHAR2,
    p_action_type VARCHAR2,
    p_target      VARCHAR2,
    p_details     VARCHAR2,
    p_status      VARCHAR2 DEFAULT 'SUCCESS',
    p_error       VARCHAR2 DEFAULT NULL
  ) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_mode VARCHAR2(10) := CASE WHEN g_dry_run THEN 'DRY_RUN' ELSE 'EXECUTE' END;
  BEGIN
    INSERT INTO security_remediation_log
      (run_mode, category, action_type, target_object, details, status, error_message)
    VALUES
      (v_mode, p_category, p_action_type, p_target, p_details, p_status, p_error);
    COMMIT;

    -- Console output
    DBMS_OUTPUT.PUT_LINE(
      RPAD(v_mode, 10) || ' | ' ||
      RPAD(p_category, 15) || ' | ' ||
      RPAD(p_action_type, 20) || ' | ' ||
      RPAD(NVL(p_target, '-'), 30) || ' | ' ||
      p_status
    );
  END log_action;

  -- ===========================================================================
  -- UTILITY: Check Excluded User
  -- ===========================================================================
  FUNCTION is_excluded_user(p_username VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    RETURN INSTR(',' || UPPER(g_exclude_users) || ',', ',' || UPPER(p_username) || ',') > 0;
  END is_excluded_user;

  -- ===========================================================================
  -- 1. REVOKE DANGEROUS PRIVILEGES
  -- ===========================================================================
  PROCEDURE revoke_dangerous_privileges IS
    CURSOR c_privs IS
      SELECT grantee, privilege
      FROM dba_sys_privs
      WHERE privilege IN (
        'DBA', 'ALTER SYSTEM', 'DROP ANY TABLE', 'ALTER ANY TABLE',
        'DELETE ANY TABLE', 'INSERT ANY TABLE', 'UPDATE ANY TABLE',
        'CREATE ANY DIRECTORY', 'GRANT ANY PRIVILEGE', 'GRANT ANY ROLE',
        'ALTER DATABASE', 'CREATE ANY TRIGGER', 'EXECUTE ANY PROCEDURE',
        'SELECT ANY TABLE', 'CREATE ANY TABLE'
      )
      ORDER BY grantee, privilege;

    v_sql VARCHAR2(500);
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 1: Revoking Dangerous Privileges ===' || CHR(10));

    FOR r IN c_privs LOOP
      IF NOT is_excluded_user(r.grantee) THEN
        g_issues_found := g_issues_found + 1;
        v_sql := 'REVOKE ' || r.privilege || ' FROM ' || r.grantee;

        IF NOT g_dry_run THEN
          BEGIN
            EXECUTE IMMEDIATE v_sql;
            g_issues_fixed := g_issues_fixed + 1;
            log_action('PRIVILEGES', 'REVOKE', r.grantee, r.privilege, 'FIXED');
          EXCEPTION
            WHEN OTHERS THEN
              log_action('PRIVILEGES', 'REVOKE', r.grantee, r.privilege, 'ERROR', SQLERRM);
          END;
        ELSE
          log_action('PRIVILEGES', 'REVOKE', r.grantee, r.privilege, 'WOULD_FIX');
        END IF;
      END IF;
    END LOOP;
  END revoke_dangerous_privileges;

  -- ===========================================================================
  -- 2. REVOKE PUBLIC GRANTS
  -- ===========================================================================
  PROCEDURE revoke_public_grants IS
    CURSOR c_public IS
      SELECT owner, table_name, privilege
      FROM dba_tab_privs
      WHERE grantee = 'PUBLIC'
        AND owner NOT IN ('SYS', 'SYSTEM', 'XDB', 'CTXSYS', 'MDSYS',
                          'ORDSYS', 'WMSYS', 'ORDDATA', 'LBACSYS')
        AND privilege IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'EXECUTE')
      ORDER BY owner, table_name;

    v_sql VARCHAR2(500);
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 2: Revoking PUBLIC Grants ===' || CHR(10));

    FOR r IN c_public LOOP
      g_issues_found := g_issues_found + 1;
      v_sql := 'REVOKE ' || r.privilege || ' ON ' ||
               r.owner || '.' || r.table_name || ' FROM PUBLIC';

      IF NOT g_dry_run THEN
        BEGIN
          EXECUTE IMMEDIATE v_sql;
          g_issues_fixed := g_issues_fixed + 1;
          log_action('PUBLIC_GRANTS', 'REVOKE', r.owner || '.' || r.table_name, r.privilege, 'FIXED');
        EXCEPTION
          WHEN OTHERS THEN
            log_action('PUBLIC_GRANTS', 'REVOKE', r.owner || '.' || r.table_name, r.privilege, 'ERROR', SQLERRM);
        END;
      ELSE
        log_action('PUBLIC_GRANTS', 'REVOKE', r.owner || '.' || r.table_name, r.privilege, 'WOULD_FIX');
      END IF;
    END LOOP;
  END revoke_public_grants;

  -- ===========================================================================
  -- 3. LOCK INACTIVE ACCOUNTS
  -- ===========================================================================
  PROCEDURE lock_inactive_accounts IS
    CURSOR c_inactive IS
      SELECT u.username, u.last_login, u.account_status
      FROM dba_users u
      WHERE u.account_status = 'OPEN'
        AND u.username NOT IN (SELECT TRIM(REGEXP_SUBSTR(g_exclude_users, '[^,]+', 1, LEVEL))
                               FROM dual
                               CONNECT BY REGEXP_SUBSTR(g_exclude_users, '[^,]+', 1, LEVEL) IS NOT NULL)
        AND (u.last_login IS NULL OR u.last_login < SYSDATE - &INACTIVE_DAYS)
        AND NOT EXISTS (
          SELECT 1 FROM unified_audit_trail a
          WHERE a.dbusername = u.username
            AND a.event_timestamp > SYSDATE - &INACTIVE_DAYS
        )
      ORDER BY u.username;

    v_sql VARCHAR2(200);
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 3: Locking Inactive Accounts (>' || &INACTIVE_DAYS || ' days) ===' || CHR(10));

    FOR r IN c_inactive LOOP
      g_issues_found := g_issues_found + 1;
      v_sql := 'ALTER USER ' || r.username || ' ACCOUNT LOCK';

      IF NOT g_dry_run THEN
        BEGIN
          EXECUTE IMMEDIATE v_sql;
          g_issues_fixed := g_issues_fixed + 1;
          log_action('ACCOUNTS', 'LOCK', r.username,
                     'Last login: ' || NVL(TO_CHAR(r.last_login, 'YYYY-MM-DD'), 'NEVER'), 'FIXED');
        EXCEPTION
          WHEN OTHERS THEN
            log_action('ACCOUNTS', 'LOCK', r.username, NULL, 'ERROR', SQLERRM);
        END;
      ELSE
        log_action('ACCOUNTS', 'LOCK', r.username,
                   'Last login: ' || NVL(TO_CHAR(r.last_login, 'YYYY-MM-DD'), 'NEVER'), 'WOULD_FIX');
      END IF;
    END LOOP;
  END lock_inactive_accounts;

  -- ===========================================================================
  -- 4. ENFORCE PASSWORD POLICY
  -- ===========================================================================
  PROCEDURE enforce_password_policy IS
    v_profile_exists NUMBER;
    v_sql VARCHAR2(1000);
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 4: Enforcing Password Policy ===' || CHR(10));

    -- Check if secure profile exists
    SELECT COUNT(*) INTO v_profile_exists
    FROM dba_profiles WHERE profile = 'SECURE_APP_PROFILE' AND ROWNUM = 1;

    IF v_profile_exists = 0 THEN
      g_issues_found := g_issues_found + 1;

      IF NOT g_dry_run THEN
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE PROFILE secure_app_profile LIMIT
              PASSWORD_LIFE_TIME 90
              PASSWORD_REUSE_TIME 365
              PASSWORD_REUSE_MAX 12
              PASSWORD_VERIFY_FUNCTION ora12c_strong_verify_function
              FAILED_LOGIN_ATTEMPTS 5
              PASSWORD_LOCK_TIME UNLIMITED
              PASSWORD_GRACE_TIME 7';
          g_issues_fixed := g_issues_fixed + 1;
          log_action('PASSWORD', 'CREATE_PROFILE', 'SECURE_APP_PROFILE',
                     '90-day expiry, 5 failed attempts lock', 'FIXED');
        EXCEPTION
          WHEN OTHERS THEN
            log_action('PASSWORD', 'CREATE_PROFILE', 'SECURE_APP_PROFILE', NULL, 'ERROR', SQLERRM);
        END;
      ELSE
        log_action('PASSWORD', 'CREATE_PROFILE', 'SECURE_APP_PROFILE',
                   '90-day expiry, 5 failed attempts lock', 'WOULD_FIX');
      END IF;
    ELSE
      log_action('PASSWORD', 'CHECK_PROFILE', 'SECURE_APP_PROFILE', 'Already exists', 'OK');
    END IF;

    -- Apply profile to users with DEFAULT profile
    FOR r IN (SELECT username FROM dba_users
              WHERE profile = 'DEFAULT'
                AND account_status = 'OPEN'
                AND username NOT IN (SELECT TRIM(REGEXP_SUBSTR(g_exclude_users, '[^,]+', 1, LEVEL))
                                     FROM dual
                                     CONNECT BY REGEXP_SUBSTR(g_exclude_users, '[^,]+', 1, LEVEL) IS NOT NULL))
    LOOP
      g_issues_found := g_issues_found + 1;

      IF NOT g_dry_run AND v_profile_exists > 0 THEN
        BEGIN
          EXECUTE IMMEDIATE 'ALTER USER ' || r.username || ' PROFILE secure_app_profile';
          g_issues_fixed := g_issues_fixed + 1;
          log_action('PASSWORD', 'APPLY_PROFILE', r.username, 'Applied secure_app_profile', 'FIXED');
        EXCEPTION
          WHEN OTHERS THEN
            log_action('PASSWORD', 'APPLY_PROFILE', r.username, NULL, 'ERROR', SQLERRM);
        END;
      ELSE
        log_action('PASSWORD', 'APPLY_PROFILE', r.username, 'Would apply secure_app_profile', 'WOULD_FIX');
      END IF;
    END LOOP;
  END enforce_password_policy;

  -- ===========================================================================
  -- 5. ENABLE AUDIT POLICIES
  -- ===========================================================================
  PROCEDURE enable_audit_policies IS
    v_policy_exists NUMBER;

    TYPE t_policies IS TABLE OF VARCHAR2(100);
    v_builtin_policies t_policies := t_policies(
      'ORA_LOGON_FAILURES',
      'ORA_SECURECONFIG',
      'ORA_DBA_POLICY'
    );
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 5: Enabling Audit Policies ===' || CHR(10));

    -- Enable built-in policies
    FOR i IN 1..v_builtin_policies.COUNT LOOP
      SELECT COUNT(*) INTO v_policy_exists
      FROM audit_unified_enabled_policies
      WHERE policy_name = v_builtin_policies(i);

      IF v_policy_exists = 0 THEN
        g_issues_found := g_issues_found + 1;

        IF NOT g_dry_run THEN
          BEGIN
            EXECUTE IMMEDIATE 'AUDIT POLICY ' || v_builtin_policies(i);
            g_issues_fixed := g_issues_fixed + 1;
            log_action('AUDITING', 'ENABLE_POLICY', v_builtin_policies(i), 'Built-in policy enabled', 'FIXED');
          EXCEPTION
            WHEN OTHERS THEN
              log_action('AUDITING', 'ENABLE_POLICY', v_builtin_policies(i), NULL, 'ERROR', SQLERRM);
          END;
        ELSE
          log_action('AUDITING', 'ENABLE_POLICY', v_builtin_policies(i), 'Built-in policy', 'WOULD_FIX');
        END IF;
      ELSE
        log_action('AUDITING', 'CHECK_POLICY', v_builtin_policies(i), 'Already enabled', 'OK');
      END IF;
    END LOOP;

    -- Create custom security audit policy
    SELECT COUNT(*) INTO v_policy_exists
    FROM audit_unified_policies
    WHERE policy_name = 'SECURITY_REMEDIATION_POLICY';

    IF v_policy_exists = 0 THEN
      g_issues_found := g_issues_found + 1;

      IF NOT g_dry_run THEN
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE AUDIT POLICY security_remediation_policy
              ACTIONS
                ALTER SYSTEM, ALTER DATABASE,
                CREATE USER, ALTER USER, DROP USER,
                GRANT, REVOKE,
                CREATE ROLE, ALTER ROLE, DROP ROLE,
                CREATE DIRECTORY, DROP DIRECTORY';
          EXECUTE IMMEDIATE 'AUDIT POLICY security_remediation_policy';
          g_issues_fixed := g_issues_fixed + 1;
          log_action('AUDITING', 'CREATE_POLICY', 'SECURITY_REMEDIATION_POLICY',
                     'Custom security policy created and enabled', 'FIXED');
        EXCEPTION
          WHEN OTHERS THEN
            log_action('AUDITING', 'CREATE_POLICY', 'SECURITY_REMEDIATION_POLICY', NULL, 'ERROR', SQLERRM);
        END;
      ELSE
        log_action('AUDITING', 'CREATE_POLICY', 'SECURITY_REMEDIATION_POLICY',
                   'Would create custom policy', 'WOULD_FIX');
      END IF;
    ELSE
      log_action('AUDITING', 'CHECK_POLICY', 'SECURITY_REMEDIATION_POLICY', 'Already exists', 'OK');
    END IF;
  END enable_audit_policies;

  -- ===========================================================================
  -- 6. SETUP DATA REDACTION (Template - requires customization)
  -- ===========================================================================
  PROCEDURE setup_data_redaction IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '=== PHASE 6: Data Redaction Setup ===' || CHR(10));

    -- This is a template - actual implementation depends on schema
    log_action('REDACTION', 'INFO', NULL,
               'Data redaction requires schema-specific configuration. ' ||
               'Identify PII columns and create policies manually.', 'SKIPPED');

    -- Example query to find potential PII columns
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Run this query to find potential PII columns:');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('SELECT owner, table_name, column_name');
    DBMS_OUTPUT.PUT_LINE('FROM dba_tab_columns');
    DBMS_OUTPUT.PUT_LINE('WHERE REGEXP_LIKE(column_name, ''(EMAIL|PHONE|SSN|TAX|SALARY|ADDRESS|DOB|BIRTH)'', ''i'')');
    DBMS_OUTPUT.PUT_LINE('  AND owner NOT IN (''SYS'', ''SYSTEM'');');
    DBMS_OUTPUT.PUT_LINE('');
  END setup_data_redaction;

  -- ===========================================================================
  -- GENERATE FINAL REPORT
  -- ===========================================================================
  PROCEDURE generate_report IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10));
    DBMS_OUTPUT.PUT_LINE('╔══════════════════════════════════════════════════════════════════╗');
    DBMS_OUTPUT.PUT_LINE('║             SECURITY REMEDIATION SUMMARY REPORT                  ║');
    DBMS_OUTPUT.PUT_LINE('╠══════════════════════════════════════════════════════════════════╣');
    DBMS_OUTPUT.PUT_LINE('║  Run Mode:      ' || RPAD(CASE WHEN g_dry_run THEN 'DRY RUN (No changes made)' ELSE 'EXECUTE (Changes applied)' END, 48) || '║');
    DBMS_OUTPUT.PUT_LINE('║  Run ID:        ' || RPAD(g_run_id, 48) || '║');
    DBMS_OUTPUT.PUT_LINE('║  Timestamp:     ' || RPAD(TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'), 48) || '║');
    DBMS_OUTPUT.PUT_LINE('╠══════════════════════════════════════════════════════════════════╣');
    DBMS_OUTPUT.PUT_LINE('║  Issues Found:  ' || RPAD(TO_CHAR(g_issues_found), 48) || '║');
    DBMS_OUTPUT.PUT_LINE('║  Issues Fixed:  ' || RPAD(TO_CHAR(g_issues_fixed), 48) || '║');
    DBMS_OUTPUT.PUT_LINE('║  Issues Skipped:' || RPAD(TO_CHAR(g_issues_found - g_issues_fixed), 48) || '║');
    DBMS_OUTPUT.PUT_LINE('╠══════════════════════════════════════════════════════════════════╣');

    IF g_dry_run THEN
      DBMS_OUTPUT.PUT_LINE('║  ⚠  DRY RUN COMPLETE - No changes were made                     ║');
      DBMS_OUTPUT.PUT_LINE('║  ⚠  To apply fixes, set DRY_RUN = FALSE and re-run              ║');
    ELSE
      DBMS_OUTPUT.PUT_LINE('║  ✓  REMEDIATION COMPLETE - Changes have been applied            ║');
    END IF;

    DBMS_OUTPUT.PUT_LINE('╚══════════════════════════════════════════════════════════════════╝');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('View full log: SELECT * FROM security_remediation_log ORDER BY log_id DESC;');
    DBMS_OUTPUT.PUT_LINE('');
  END generate_report;

  -- ===========================================================================
  -- MAIN: RUN FULL REMEDIATION
  -- ===========================================================================
  PROCEDURE run_full_remediation IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('╔══════════════════════════════════════════════════════════════════╗');
    DBMS_OUTPUT.PUT_LINE('║       ORACLE DATABASE SECURITY REMEDIATION - STARTING            ║');
    DBMS_OUTPUT.PUT_LINE('║                                                                  ║');
    IF g_dry_run THEN
      DBMS_OUTPUT.PUT_LINE('║       >>> RUNNING IN DRY-RUN MODE (No changes will be made) <<< ║');
    ELSE
      DBMS_OUTPUT.PUT_LINE('║       >>> RUNNING IN EXECUTE MODE (Changes WILL be applied) <<< ║');
    END IF;
    DBMS_OUTPUT.PUT_LINE('╚══════════════════════════════════════════════════════════════════╝');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE(RPAD('MODE', 10) || ' | ' || RPAD('CATEGORY', 15) || ' | ' ||
                         RPAD('ACTION', 20) || ' | ' || RPAD('TARGET', 30) || ' | STATUS');
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 100, '-'));

    -- Run all phases
    revoke_dangerous_privileges;
    revoke_public_grants;
    lock_inactive_accounts;
    enforce_password_policy;
    enable_audit_policies;
    setup_data_redaction;

    -- Final report
    generate_report;

  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('FATAL ERROR: ' || SQLERRM);
      DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
      RAISE;
  END run_full_remediation;

END security_remediation;
/

-- ============================================================================
-- EXECUTE REMEDIATION
-- ============================================================================
BEGIN
  security_remediation.run_full_remediation;
END;
/

/*
================================================================================
  POST-REMEDIATION VERIFICATION QUERIES
================================================================================
*/

PROMPT
PROMPT === Verification Queries ===
PROMPT

-- Check remaining dangerous privileges
PROMPT Remaining dangerous privileges (should be empty or system users only):
SELECT grantee, privilege FROM dba_sys_privs
WHERE privilege IN ('DBA', 'ALTER SYSTEM', 'DROP ANY TABLE')
  AND grantee NOT IN ('SYS', 'SYSTEM', 'ADMIN')
ORDER BY grantee;

-- Check audit policies
PROMPT Enabled audit policies:
SELECT policy_name, enabled_option, entity_name
FROM audit_unified_enabled_policies
ORDER BY policy_name;

-- Check locked accounts
PROMPT Recently locked accounts:
SELECT username, account_status, lock_date
FROM dba_users
WHERE account_status LIKE '%LOCKED%'
  AND lock_date > SYSDATE - 1
ORDER BY lock_date DESC;

/*
================================================================================
  ROLLBACK PROCEDURES (if needed)
================================================================================

-- Unlock a specific user:
ALTER USER username ACCOUNT UNLOCK;

-- Re-grant a privilege:
GRANT privilege_name TO username;

-- Disable an audit policy:
NOAUDIT POLICY policy_name;

-- View all changes made:
SELECT * FROM security_remediation_log
WHERE run_mode = 'EXECUTE'
ORDER BY log_id DESC;

================================================================================
*/
